#!/usr/bin/env node
// Embeds the PDF fonts and logo into src/assets.js as base64, so the same code
// runs in the Worker and in Node tests without bundler file rules.
//
//   node tools/embed-assets.mjs          write src/assets.js
//   node tools/embed-assets.mjs --check  fail if src/assets.js is out of date
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const files = {
  fontRegular: 'assets/IBMPlexSansHebrew-Regular.ttf',
  fontBold: 'assets/IBMPlexSansHebrew-SemiBold.ttf',
  logoPng: 'assets/logo.png',
};

let out = '// Generated by tools/embed-assets.mjs. Do not edit.\n' +
  '// IBM Plex Sans Hebrew: SIL Open Font License 1.1 (assets/LICENSE-IBM-Plex.txt).\n';
for (const [name, file] of Object.entries(files)) {
  out += `export const ${name} = '${fs.readFileSync(path.join(root, file)).toString('base64')}';\n`;
}

const target = path.join(root, 'src/assets.js');
if (process.argv.includes('--check')) {
  const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
  if (current !== out) {
    console.error('src/assets.js is stale: run node workers/pay/tools/embed-assets.mjs');
    process.exit(1);
  }
  console.log('PDF assets are current.');
} else {
  fs.writeFileSync(target, out);
  console.log('Wrote src/assets.js');
}
