(async()=>{
 if(location.hash && !new URLSearchParams(location.search).has('booking') && !new URLSearchParams(location.search).has('reschedule'))return;
 const $=s=>document.querySelector(s),query=new URLSearchParams(location.search),api=window.CrownAPI;
 const make=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
 const error=text=>$('#page-error').textContent=text;
 const button=(text,fn)=>{const b=make('button',text,'booking-button');b.type='button';b.addEventListener('click',fn);return b;};
 const call=(path,method='GET',data)=>api.request(path,{method,data,publicRequest:true});
 $('header>span').textContent='Book a meeting';$('.preview-notice').hidden=true;$('#page-description').textContent='Choose a meeting and a time that works for you.';
 try{
  if(!await api.ready)throw Error('Online booking is not connected yet. Please contact the host.');
  if(query.has('booking')){await manage();return;}
  const slug=query.get('user');if(!slug)throw Error('This booking link is incomplete.');
  const host=await call('/public/'+encodeURIComponent(slug));
  for(const [key,variable] of [['accent','--page-accent'],['background','--page-bg'],['text','--page-text']])document.documentElement.style.setProperty(variable,host[key]);
  for(const kind of ['logo','photo'])if(host[kind]){const image=make('img');image.src=host[kind];image.alt=kind==='logo'?'Host logo':'Host profile photo';image.className='host-'+kind;$('#host-name').before(image);}
  $('#host-name').textContent=`Meet with ${host.pageName}`;
  const zone=Intl.DateTimeFormat().resolvedOptions().timeZone;
  for(const meeting of host.meetings.filter(m=>!query.get('meeting')||m.id===query.get('meeting'))){
   const card=make('section','','public-meeting');card.append(make('h2',meeting.title),make('p',`${meeting.duration} minutes${meeting.location?' - '+meeting.location:''}`),make('p',meeting.description));
   const open=button('Choose a time',()=>showScheduler(card,meeting,slug,zone));card.append(open);$('#public-meetings').append(card);
  }
 }catch(e){error(e.message);}
 async function showScheduler(card,meeting,slug,initialZone){
  card.querySelector('.booking-scheduler')?.remove();const panel=make('div','','booking-scheduler');card.append(panel);let revision=0;
  const label=make('label','Your time zone'),zone=make('select');for(const item of ['UTC',...Intl.supportedValuesOf('timeZone')]){const option=make('option',item.replaceAll('_',' '));option.value=item;zone.append(option);}zone.value=initialZone;label.append(zone);
  const dateLabel=make('label','Starting date'),date=make('input');date.type='date';date.value=new Date().toLocaleDateString('en-CA');dateLabel.append(date);
  const controls=make('div','','booking-controls'),status=make('p','','booking-status'),grid=make('div','','booking-slot-grid'),days=make('div','','booking-days'),formArea=make('div');status.setAttribute('role','status');
  controls.append(label,dateLabel,button('Show times',load));panel.append(controls,status,days,grid,formArea);zone.addEventListener('change',load);date.addEventListener('change',load);await load();
  async function load(){const current=++revision;status.textContent='Checking availability...';grid.replaceChildren();days.replaceChildren();formArea.replaceChildren();try{const result=await call(`/public/${encodeURIComponent(slug)}/slots?${new URLSearchParams({meeting:meeting.id,from:date.value,days:'7',timezone:zone.value})}`);if(current!==revision)return;status.textContent=result.slots.length?'Available times for the next seven days.':'No available times in these seven days. Choose another date.';const groups=new Map();for(const slot of result.slots){const key=new Date(slot.start).toLocaleDateString('en-CA',{timeZone:zone.value});if(!groups.has(key))groups.set(key,[]);groups.get(key).push(slot);}
   function choose(key,selectedButton){grid.replaceChildren();formArea.replaceChildren();for(const b of days.children)b.setAttribute('aria-pressed',String(b===selectedButton));for(const slot of groups.get(key)){const text=new Date(slot.start).toLocaleTimeString(undefined,{timeZone:zone.value,hour:'2-digit',minute:'2-digit'});grid.append(button(text,()=>bookingForm(slot)));}}
   for(const [key,values] of groups){const text=new Date(values[0].start).toLocaleDateString(undefined,{timeZone:zone.value,weekday:'short',month:'short',day:'numeric'});const b=button(text,()=>choose(key,b));days.append(b);if(days.children.length===1)choose(key,b);}
   const next=button('Next 7 days',()=>{const nextDate=new Date(date.value+'T12:00:00');nextDate.setDate(nextDate.getDate()+7);date.value=nextDate.toLocaleDateString('en-CA');load();});days.append(next);
   }catch(e){if(current===revision)status.textContent=e.message;}}
  function bookingForm(slot){
   formArea.replaceChildren();const form=make('form','','guest-form'),heading=make('h3',new Date(slot.start).toLocaleString(undefined,{timeZone:zone.value,dateStyle:'full',timeStyle:'short'}));form.append(heading);
   const inputs={};for(const [key,title,type,max] of [['name','Your name','text',100],['email','Email address','email',254],['notes','Anything the host should know?','text',2000]]){const label=make('label',title),input=make(key==='notes'?'textarea':'input');if(key!=='notes')input.type=type;input.required=key!=='notes';input.maxLength=max;input.autocomplete=key==='notes'?'off':key;label.append(input);form.append(label);inputs[key]=input;}
   const captcha=make('div'),notice=make('p','','booking-status'),submit=make('button','Confirm booking','booking-button');submit.type='submit';notice.setAttribute('role','status');form.append(captcha,submit,notice);formArea.append(form);let requestId=crypto.randomUUID(),captchaToken='',widget=null;
   if(api.config.turnstileSiteKey){loadTurnstile().then(()=>{if(!form.isConnected)return;widget=window.turnstile.render(captcha,{sitekey:api.config.turnstileSiteKey,callback:token=>captchaToken=token,'expired-callback':()=>captchaToken=''});}).catch(()=>notice.textContent='Booking verification could not load. Please refresh.');}
   form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;submit.disabled=true;notice.textContent='Confirming with the calendar...';try{const result=await call(`/public/${encodeURIComponent(slug)}/book`,'POST',{meetingId:meeting.id,start:slot.start,requestId,name:inputs.name.value.trim(),email:inputs.email.value.trim(),notes:inputs.notes.value,turnstileToken:captchaToken,...(query.has('reschedule')?{previousId:query.get('reschedule'),rescheduleToken:location.hash.slice(1)}:{})});form.replaceChildren(make('h3','Your meeting is confirmed'),make('p',new Date(result.start).toLocaleString(undefined,{timeZone:zone.value,dateStyle:'full',timeStyle:'short'})),make('p','The calendar invitation has been requested for your email. Keep the link below to manage your booking.'));const manage=make('a','Manage or cancel booking','booking-button');manage.href=`/calendar/meet/?booking=${encodeURIComponent(result.id)}#${result.manageToken}`;form.append(manage,button('Download calendar file',()=>downloadICS(meeting,result)));status.textContent='Booking confirmed.';}catch(e){notice.textContent=e.message;if(widget!==null){window.turnstile.reset(widget);captchaToken='';}if(e.status===409)requestId=crypto.randomUUID();}finally{submit.disabled=false;}});
   inputs.name.focus();
  }
 }
 async function manage(){const id=query.get('booking'),token=location.hash.slice(1);const result=await call(`/booking/${encodeURIComponent(id)}?token=${encodeURIComponent(token)}`);$('#host-name').textContent=result.title;$('#page-description').textContent=`${new Date(result.start).toLocaleString()} - ${result.status}`;if(result.status==='confirmed'&&result.slug){const link=make('a','Choose a new time','booking-button');link.href=`/calendar/meet/?user=${encodeURIComponent(result.slug)}&meeting=${encodeURIComponent(result.meetingId)}&reschedule=${encodeURIComponent(id)}#${token}`;$('#public-meetings').append(link);}
  if(result.status==='confirmed')$('#public-meetings').append(button('Cancel booking',async event=>{const b=event.currentTarget;b.disabled=true;try{await call(`/booking/${encodeURIComponent(id)}/cancel`,'POST',{token});$('#page-description').textContent='Your booking has been cancelled.';b.remove();}catch(e){error(e.message);b.disabled=false;}}));}
 function downloadICS(meeting,booking){const escape=value=>String(value||'').replaceAll('\\','\\\\').replaceAll('\n','\\n').replaceAll(',','\\,').replaceAll(';','\\;').replaceAll('\r','');const stamp=value=>new Date(value).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Red Crown Interactive//Calendar//EN','BEGIN:VEVENT',`UID:${booking.id}@redcrowninteractive.com`,`DTSTAMP:${stamp(Date.now())}`,`DTSTART:${stamp(booking.start)}`,`DTEND:${stamp(booking.end)}`,`SUMMARY:${escape(meeting.title)}`,`LOCATION:${escape(meeting.location)}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/calendar'})),link=make('a');link.href=url;link.download='meeting.ics';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 let turnstilePromise;function loadTurnstile(){return turnstilePromise??=new Promise((resolve,reject)=>{if(window.turnstile)return resolve();const script=make('script');script.src='https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';script.onload=resolve;script.onerror=reject;document.head.append(script);});}
})();
