from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]

PAGES = [
    dict(slug="vr-development", title="פיתוח מציאות מדומה לעסקים", eyebrow="פיתוח מציאות מדומה ורבודה בהתאמה לארגון", lead="לא עוד הדגמת טכנולוגיה. מערכת יציבה שמשרתת תהליך אמיתי — מהאפיון, דרך חוויית המשתמש והתלת־ממד, ועד התקנה והטמעה.", project="VR / מציאות משולבת", image="/assets/work-vr-fugacity.webp", case="מעבדה וירטואלית פעילה שמאפשרת לסטודנטים לתרגל ניסוי מורכב בסביבה בטוחה ומבוקרת.", bullets=["פיתוח למשקפי מציאות מדומה ומציאות משולבת", "חיבור למערכות, נתונים ותהליכים קיימים", "פיילוט ממוקד לפני הרחבה מלאה"], uses=[("הדרכה ותרגול","תרחישים אינטראקטיביים עם משוב, מדידה ושליטה למדריכים."),("המחשת מוצר","הצגת מערכות, חללים ותהליכים שאי אפשר להביא לחדר."),("מחקר וניסויים","סביבה מבוקרת לאיסוף נתונים ולשחזור עקבי של תרחישים.")]),
    dict(slug="training-simulations", title="סימולציות הדרכה לעובדים", eyebrow="תרגול מורכב בלי לסכן אנשים, ציוד או זמן ייצור", lead="בונים סביבת הדרכה אינטראקטיבית שמאפשרת לעובדים לתרגל החלטות ותהליכים, ולמדריכים לראות התקדמות — במחשב או במשקפי מציאות מדומה.", project="סימולציות והדרכה", image="/assets/work-class-setup.webp", case="מערכת כיתתית פעילה עם עד 12 משקפיים, הפעלה מרוכזת וכלים למדריך.", bullets=["תרחישים, ניקוד ומשוב לפי יעדי ההדרכה", "מערכת ניהול והפעלה למדריכים", "הטמעה מדורגת בארגון"], uses=[("בטיחות ותפעול","תרגול מצבי קיצון ונהלים בלי לעצור קו או לסכן עובד."),("הכשרת עובדים","חזרה עקבית על תהליך עד להשגת רמת ביצוע נדרשת."),("מעבדות וכיתות","הפעלה סימולטנית, שליטה בתוכן ותמיכה במדריך.")]),
    dict(slug="interactive-3d", title="פיתוח תוכנה אינטראקטיבית בתלת־ממד", eyebrow="גרפיקה והנדסת תוכנה שנבנות כמוצר אחד", lead="יישומי תלת־ממד בזמן אמת למחשב, לנייד ולמציאות משולבת — עם קוד יציב, ממשק ברור וביצועים שמתאימים להפעלה אמיתית.", project="תלת־ממד ותוכנה", image="/assets/work-ar-enzymatic.webp", case="מערכת אינטראקטיבית שמחברת מודל תלת־ממדי, חישוב מדעי וחוויית שימוש ברורה.", bullets=["ארכיטקטורה שניתנת להרחבה", "אופטימיזציה לחומרת היעד", "חיבור למידע, שירותים וחישובים"], uses=[("הדמיה הנדסית","הפיכת מידע ומבנים מורכבים לכלי שאפשר לחקור ולהפעיל."),("קונפיגורטורים","הצגת אפשרויות מוצר ותוצאות באופן חזותי ואינטראקטיבי."),("כלים מקצועיים","ממשקים תלת־ממדיים לעבודה, בדיקה, תכנון וקבלת החלטות.")]),
    dict(slug="research-software", title="פיתוח תוכנה למחקר והנדסה", eyebrow="ממודל מדעי לכלי שאנשים באמת יכולים להשתמש בו", lead="מחברים חישוב, נתונים ותלת־ממד בזמן אמת למערכת מחקר יציבה — בלי לאבד את הדיוק המדעי ובלי להשאיר את המשתמש מול אב־טיפוס טכני.", project="תוכנה למחקר", image="/assets/work-ml-livemol.webp", case="כלי מחקר חזותי שמחבר חישוב מדעי ותצוגת מולקולות אינטראקטיבית בסביבת עבודה אחת.", bullets=["חיבור בין חישוב מדעי לממשק אינטראקטיבי", "כלים למעבדות, מוסדות וחברות הנדסיות", "תכנון לניסוי, הדגמה או שימוש מתמשך"], uses=[("כלי מחקר חזותיים","הצגת תוצאות ומודלים בצורה שאפשר לחקור, להשוות ולהסביר."),("מערכות ניסוי","שליטה בפרוטוקול, תרחישים ואיסוף נתונים באופן עקבי."),("המחשה מדעית","הפיכת חישובים מורכבים לחוויה ברורה לחוקרים ולבעלי עניין.")]),
]

TEMPLATE = '''<!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0e080a">
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-18313532220"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments)}}gtag('js',new Date());gtag('config','AW-18313532220');</script>
<title>{title} | Red Crown Interactive</title><meta name="description" content="{description}"><link rel="canonical" href="https://redcrowninteractive.com/he/{slug}/"><link rel="icon" href="/favicon.ico"><link rel="stylesheet" href="/site.css"><link rel="stylesheet" href="/he/solutions.css">
<meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:url" content="https://redcrowninteractive.com/he/{slug}/"><meta property="og:image" content="https://redcrowninteractive.com/og-image.png"><meta property="og:type" content="website">
<script type="application/ld+json">{{"@context":"https://schema.org","@type":"Service","name":"{title}","provider":{{"@type":"Organization","name":"Red Crown Interactive","url":"https://redcrowninteractive.com/"}},"areaServed":"IL","url":"https://redcrowninteractive.com/he/{slug}/"}}</script></head><body>
<header class="wrap top"><a href="/he/"><img src="/assets/logo-kit/redcrown-lockup-stacked-white-scarlet.svg" alt="Red Crown Interactive"></a><nav aria-label="ניווט"><a href="#solutions">פתרונות</a><a href="#case">ניסיון</a><a href="#contact">בדיקת היתכנות</a></nav></header>
<main><section class="wrap hero"><div><div class="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{lead}</p><div class="hero-actions"><a class="btn" href="#contact">בדיקת היתכנות ראשונית</a><span class="quiet">שיחה ישירה עם המפתחת שמובילה את הפרויקט</span></div></div><aside class="proof"><h2>מה מקבלים</h2><ul>{bullets}</ul></aside></section>
<div class="strip"><div class="wrap"><b>למעלה מעשור בפיתוח מערכות זמן אמת</b> · ניסיון במחקר, טכנולוגיה רפואית, משחקים וביטחון · עבודה מהאפיון ועד ההטמעה</div></div>
<section class="wrap" id="solutions"><h2 class="section-title">פתרון לפי הבעיה, לא לפי מילת אופנה</h2><p class="section-lead">מתחילים מהתוצאה שהארגון צריך. רק אחר כך מחליטים אם הפתרון הנכון הוא מחשב, נייד, מציאות מדומה או מערכת משולבת.</p><div class="cards">{uses}</div></section>
<section class="wrap case" id="case"><img src="{image}" alt="פרויקט רלוונטי של Red Crown Interactive" loading="lazy"><div><div class="eyebrow">ניסיון רלוונטי · {project}</div><h2 class="section-title">מערכות שנבנו להפעלה אמיתית</h2><p class="section-lead">{case}</p><ul><li>אפיון טכני וחוויית משתמש באותו תהליך</li><li>פיתוח, תלת־ממד ואופטימיזציה תחת אחריות אחת</li><li>מסירה, הדרכה ותמיכה בהטמעה</li></ul></div></section>
<section class="wrap"><h2 class="section-title">מתחילים קטן, לומדים מהר</h2><div class="steps"><div class="step"><h3>בדיקת היתכנות</h3><p>מגדירים משתמשים, תהליך, סיכון ומדד הצלחה.</p></div><div class="step"><h3>פיילוט ממוקד</h3><p>בונים תרחיש מרכזי שמוכיח ערך לפני הרחבה.</p></div><div class="step"><h3>מערכת והטמעה</h3><p>מרחיבים, בודקים, מדריכים ומעבירים להפעלה.</p></div></div></section>
<section class="wrap" id="contact"><div class="contact"><div><div class="eyebrow">בדיקת היתכנות ראשונית</div><h2>ספרו מה אתם מנסים להשיג</h2><p>נבדוק יחד מה הדרך הנכונה לבנות את זה, מה כדאי להוכיח בפיילוט ומה נדרש כדי להגיע למערכת יציבה.</p></div><form class="contact-form" action="https://api.web3forms.com/submit" method="POST"><input type="hidden" name="access_key" value="35f8e692-deb5-4865-86a3-7a4be79eb90b"><input type="hidden" name="subject" value="Lead from {slug}"><input type="hidden" name="from_name" value="Red Crown Interactive website"><input type="hidden" name="landing_page" value="{slug}"><input type="hidden" name="utm_source"><input type="hidden" name="utm_campaign"><input type="hidden" name="utm_content"><input type="hidden" name="gclid"><input type="checkbox" name="botcheck" class="hp" tabindex="-1" autocomplete="off"><label><span>שם</span><input name="name" autocomplete="name" required></label><label><span>אימייל</span><input type="email" name="email" autocomplete="email" required></label><label><span>טלפון, אם נוח יותר</span><input type="tel" name="phone" autocomplete="tel"></label><label><span>מה תרצו לבנות? (אופציונלי)</span><textarea name="message" rows="3"></textarea></label><button class="btn" type="submit">שליחת פרטים</button><p class="form-msg form-ok" hidden>תודה, הפרטים התקבלו.</p><p class="form-msg form-err" hidden>משהו השתבש. אפשר לכתוב ל־hello@redcrowninteractive.com.</p></form></div></section></main>
<footer class="wrap">Red Crown Interactive · חיפה · <a href="mailto:hello@redcrowninteractive.com">hello@redcrowninteractive.com</a> · <a href="/he/legal/">פרטיות ונגישות</a></footer><a class="wa" href="https://wa.me/972585760550?text={wa}" target="_blank" rel="noopener">WhatsApp</a>
<script src="/site.js"></script><script>const q=new URLSearchParams(location.search);for(const n of ['utm_source','utm_campaign','utm_content','gclid']){{const e=document.querySelector(`[name="${{n}}"]`);if(e)e.value=q.get(n)||''}}</script><script data-goatcounter="https://redcrowninteractive.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script></body></html>'''

for p in PAGES:
    uses = ''.join(f'<article class="card"><h3>{escape(a)}</h3><p>{escape(b)}</p></article>' for a,b in p['uses'])
    bullets = ''.join(f'<li>{escape(x)}</li>' for x in p['bullets'])
    description = p['lead'][:155]
    wa = escape(f"שלום, אני מתעניין/ת ב{p['title']}").replace(' ', '%20')
    context = {k: v for k, v in p.items() if k not in {'uses', 'bullets'}}
    html = TEMPLATE.format(**context, uses=uses, bullets=bullets, description=escape(description), wa=wa)
    dest = ROOT / 'he' / p['slug'] / 'index.html'
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(html, encoding='utf-8')
    print(dest.relative_to(ROOT))
